export const MIN_USERNAME_LENGTH = 3;
export const MIN_MESSAGE_LENGTH = 1;

export const MAX_USERNAME_LENGTH = 30;
export const MAX_ROOM_ID_LENGTH = 128;
export const MAX_MESSAGE_LENGTH = 500;

export const MAX_TIMESTAMP = 1;

export const MESSAGE_ENCRYPTED = {
  CIPHER_MAX_LENGTH: 4096,
  IV_LENGTH: 16,
  ALGORITHM: "AES-GCM",
  ALGORITHM_LENGTH: 7,
};
