export interface EmojiDef {
  char: string;
  label: string;
}

export const EMOJIS: EmojiDef[] = [
  { char: "😀", label: "grinning" },
  { char: "😃", label: "smiling" },
  { char: "😄", label: "smile" },
  { char: "😁", label: "beaming" },
  { char: "😆", label: "laughing" },
  { char: "😅", label: "sweat smile" },
  { char: "😂", label: "joy" },
  { char: "🙂", label: "slight smile" },
  { char: "😊", label: "blush" },
  { char: "😉", label: "wink" },
  { char: "😍", label: "heart eyes" },
  { char: "😘", label: "kiss" },
  { char: "😜", label: "winky tongue" },
  { char: "🤔", label: "thinking" },
  { char: "😎", label: "cool" },
  { char: "😏", label: "smirk" },
  { char: "😡", label: "angry" },
  { char: "😢", label: "cry" },
  { char: "😭", label: "loud cry" },
  { char: "😴", label: "sleeping" },
  { char: "😱", label: "scream" },
  { char: "🤯", label: "mind blown" },
  { char: "😇", label: "innocent" },
  { char: "🙏", label: "pray" },
  { char: "👍", label: "thumbs up" },
  { char: "👎", label: "thumbs down" },
  { char: "👋", label: "wave" },
  { char: "🤝", label: "handshake" },
  { char: "👀", label: "eyes" },
  { char: "💪", label: "strong" },
  { char: "🎉", label: "tada" },
  { char: "❤️", label: "heart" },
  { char: "💔", label: "broken heart" },
  { char: "🔥", label: "fire" },
  { char: "⭐", label: "star" },
  { char: "✅", label: "check" },
  { char: "❗", label: "exclamation" },
  { char: "❓", label: "question" },
  { char: "📌", label: "pin" },
  { char: "📎", label: "paperclip" },
];
